name = 'comments'
main = "index.js"
compatibility_date = "2025-12-12"

[[durable_objects.classes]]
name = "KVStore"
class_name = "KVStore"

[[durable_objects.bindings]]
name = "KV_DO"
class_name = "KVStore"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["KVStore"]
